### ISSUE TITLE
run

### ISSUE THREAD

**Issue by Garrybrayn** [near/NEPs#501]
[ Base URL: https://explorer.mainnet.aurora.dev/api/eth-rpc ]

```[tasklist]
### Tasks
- [ ] https://github.com/near/NEPs/pull/492
- [x] https://github.com/near/NEPs/issues/502
- [ ] https://github.com/near/NEPs/issues/498
```

```[tasklist]
### Tasks
- [ ] https://github.com/near/NEPs/pull/492
```
